### ISSUE TITLE
请问您这是everything的源码，还是everythingSZ的源码？

### ISSUE THREAD

**Issue by xu-song** [yuzhengyang/Everything#2]
大神可否加个qq

**Comment by yuzhengyang** [comment]
这是以前从codeplex收藏的everythingSZ源码

**Comment by yuzhengyang** [comment]
就一普通程序员……qq:895068718

**Comment by RockNHawk** [comment]
@yuzhengyang 10 月前的那个修复【修复获取所有文件时部分文件与实际文件相比缺少的问题】是你在sz的基础上贡献的 bugfix 嘛？
感谢修复！

**Comment by yuzhengyang** [comment]
那部分代码是别人帮忙的，修复了我测试时的bug。

文件缺少的问题确实存在，问题应该是出在USN上，包括Everything也存在这个问题，磁盘上明明能看到这个文件，就是搜不出来。（这个问题很少见，还没想到怎么解决）
________________________________
发件人: shine <notifications@github.com>
发送时间: 2018年7月22日 01:58
收件人: yuzhengyang/Everything
抄送: yuzhengyang; Mention
主题: Re: [yuzhengyang/Everything] 请问您这是everything的源码，还是everythingSZ的源码？ (#2)


@yuzhengyang<https://github.com/yuzhengyang> 10 月前的那个修复【修复获取所有文件时部分文件与实际文件相比缺少的问题】是在sz的基础上贡献的 bugfix 嘛？

―

**Comment by yuzhengyang** [comment]
对了，当时问题的设备是一个优盘，转换的NTFS格式，搜不到个别文件可能和设备有关。
________________________________
发件人: shine <notifications@github.com>
发送时间: 2018年7月22日 01:58
收件人: yuzhengyang/Everything
抄送: yuzhengyang; Mention
主题: Re: [yuzhengyang/Everything] 请问您这是everything的源码，还是everythingSZ的源码？ (#2)


@yuzhengyang<https://github.com/yuzhengyang> 10 月前的那个修复【修复获取所有文件时部分文件与实际文件相比缺少的问题】是在sz的基础上贡献的 bugfix 嘛？

―

**Comment by RockNHawk** [comment]
@yuzhengyang 我正打算用这个结合 Lucene 做一个更智能的搜索，就像搜索引擎一样去索引本地文件包括全文索引，突破传统文件搜索的一些局限。我简单测试过程中，发现你们修改过后的版本能做到和 Everything 的搜索结果一模一样，之前的版本搜索结果就差很多文件。本人也是资深 .NET 开发，不过这个项目如果不是你们修复这个 BUG，乍一看还真是不知道问题出在哪，可能就要从头开始研究了。

话说你们是为什么用这个没直接用 Everyting？

**Comment by RockNHawk** [comment]
@yuzhengyang 感谢提供信息，如果我后续碰到这个问题，解决了的话，会贡献上来，大家一起来 :-)

**Comment by yuzhengyang** [comment]
@darklx 这是一个学习项目，所以就暂时到这里了。你的智能搜索创意很好，加油，期待你的项目
